spring:
  datasource:
    url: jdbc:mysql://localhost/ptu?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
    view:
      suffix: .html
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#    jackson实体转json时 为NULL不参加序列化
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.sina.com
    username: dtdhehe@sina.com
    password: xd474786105
    default-encoding: utf-8
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-wait: 30000ms     #连接池最大阻塞等待时间(负值表示没有限制)
        max-active: 100       #连接池最大连接数(负值表示没有限制)
        max-idle: 20          #连接池中最大空闲连接
        min-idle: 0           #连接池中最小空闲连接
    timeout: 3000ms
server:
  port: 9999
