spring:
  datasource:
    url: jdbc:mysql://localhost/ptu?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
    view:
      suffix: .html
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#    jackson实体转json时 为NULL不参加序列化
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.sina.com
    username: dtdhehe@sina.com
    password: xd474786105
    default-encoding: utf-8

server:
  port: 9999
